# -*- coding: utf-8 -*-
"""ee18btech11025_A1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XANjP6FDZbbCGZ3W1YeIhf8L93QsT5rr
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.array([1, 2, 3, 4, 2, 1])
N = 6 
#for h
h = np.zeros(N)
for i in range(N):
  if i-2<0:
    h[i] = (-1/2)**i
  else:
    h[i] = (-1/2)**i + (-1/2)**(i-2)

def fft(Z1, Z2, P, x, h):
  W = np.matmul(np.matmul(Z2,Z1),P)
  X1 = np.matmul(W,x)
  H1 = np.matmul(W,h)
  Y1 = np.multiply(H1,X1)
  return X1, H1, Y1

def ifft(Z1, Z2, P, Y1, N):
  W = np.matmul(np.matmul(Z2,Z1),P)
  y = (1/N)*np.matmul(W.H,Y.T)
  return y

W3 = np.exp(-1j*2*np.pi/3)
W6 = np.exp(-1j*2*np.pi/6)

Z1 = np.matrix([[W3**0,W3**0,W3**0,0,0,0],[W3**0,W3**1,W3**2,0,0,0],[W3**0,W3**2,W3**4,0,0,0],[0,0,0,W3**0,W3**0,W3**0],[0,0,0,W3**0,W3**1,W3**2],[0,0,0,W3**0,W3**2,W3**4]])
Z2 = np.matrix([[1,0,0,W6**0,0,0],[0,1,0,0,W6**1,0],[0,0,1,0,0,W6**2],[1,0,0,W6**3,0,0],[0,1,0,0,W6**4,0],[0,0,1,0,0,W6**5]])
P = np.matrix([[1,0,0,0,0,0],[0,0,1,0,0,0],[0,0,0,0,1,0],[0,1,0,0,0,0],[0,0,0,1,0,0],[0,0,0,0,0,1]])

X, H, Y = fft(Z1, Z2, P, x, h)
y = ifft(Z1, Z2, P, Y, N)

plt.figure(figsize=(15,15))
plt.subplot(3,3,2)
plt.stem(np.abs(np.array(X).ravel()),use_line_collection=True)
plt.title('$|X(k)|$')
plt.grid()

plt.subplot(3,3,3)
plt.stem(np.angle(np.array(X).ravel()),use_line_collection=True)
plt.title(r'$\angle{X(k)}$')
plt.grid()

plt.subplot(3,3,5)
plt.stem(np.abs(np.array(H).ravel()),use_line_collection=True)
plt.title('$|H(k)|$')
plt.grid()

plt.subplot(3,3,6)
plt.stem(np.angle(np.array(H).ravel()),use_line_collection=True)
plt.title(r'$\angle{H(k)}$')
plt.grid()

plt.subplot(3,3,8)
plt.stem(np.abs(np.array(Y).ravel()),use_line_collection=True)
plt.title('$|Y(k)|$')
plt.grid()

plt.subplot(3,3,9)
plt.stem(np.angle(np.array(Y).ravel()),use_line_collection=True)
plt.title(r'$\angle{Y(k)}$')
plt.grid()

plt.subplot(3,3,1)
plt.stem(x,use_line_collection=True)
plt.title(r'x(n)')
plt.grid()
plt.subplot(3,3,7)
plt.stem(np.array(y).ravel(),use_line_collection=True)
plt.title(r'y(n)')
plt.grid()
plt.subplot(3,3,4)
plt.stem(h,use_line_collection=True)
plt.title(r'h(n)')
plt.grid()
plt.savefig('A1_1.pdf')
plt.savefig('A1_1.eps')

plt.subplots_adjust(hspace=0.3,wspace=0.3)
plt.show()